services:
  pixoopal:
    image: drun555/pixoopal:latest
    container_name: pixoopal
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      PIXOO_DEVICE_ADDRESS: ${PIXOO_DEVICE_ADDRESS:-192.168.6.3}
      PIXOOPAL_INSTANCE_NAME: ${PIXOOPAL_INSTANCE_NAME:-PixooPal}
      PORT: "5173"
      DEBUG_LOGGING: ${DEBUG_LOGGING:-false}
      BODY_SIZE_LIMIT: "25M"
    volumes:
      - ./pixoopal-data:/data
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"
