name: PixooPal
version: "1.0.9"
slug: pixoopal
description: Fancy thing to control your Pixoo.
url: https://github.com/Drun555/PixooPal
arch:
  - amd64
  - aarch64
startup: application
boot: auto
image: drun555/pixoopal
hassio_api: true
ingress: true
ingress_port: 5173
panel_icon: mdi:led-strip-variant
panel_title: PixooPal
ports:
  5173/tcp: null
ports_description:
  5173/tcp: PixooPal Web UI
map:
  - type: data
    read_only: false
options:
  pixoo_device_address: ""
schema:
  pixoo_device_address: str?
environment:
  PORT: "5173"
  BODY_SIZE_LIMIT: "25M"
discovery:
  - pixoopal
watchdog: http://[HOST]:[PORT:5173]/api/v1/status
